//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace neleo_com.Logic.Bridges.Velux.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("neleo_com.Logic.Bridges.Velux.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gateway reported error &quot;{0}&quot;..
        /// </summary>
        internal static string Error_GatewayCommunication {
            get {
                return ResourceManager.GetString("Error_GatewayCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hardware gateway raised error &quot;{0}&quot;..
        /// </summary>
        internal static string Error_HardwareGateway {
            get {
                return ResourceManager.GetString("Error_HardwareGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing telegram &quot;{0}&quot; can&apos;t be sent to gateway..
        /// </summary>
        internal static string Error_OutgoingTelegram {
            get {
                return ResourceManager.GetString("Error_OutgoingTelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datagram &quot;{0}&quot; cannot be mapped to a telegram..
        /// </summary>
        internal static string Error_UnknownDatagram {
            get {
                return ResourceManager.GetString("Error_UnknownDatagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier {0}:{1} cannot be resolved..
        /// </summary>
        internal static string Error_UnknownIdentifier {
            get {
                return ResourceManager.GetString("Error_UnknownIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node, group or scene name &quot;{0}&quot; cannot be ressolved..
        /// </summary>
        internal static string Error_UnknownName {
            get {
                return ResourceManager.GetString("Error_UnknownName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming telegram &quot;{0}&quot; is not supported..
        /// </summary>
        internal static string Error_UnsupportedTelegram {
            get {
                return ResourceManager.GetString("Error_UnsupportedTelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway ({0}:51200) does not respond..
        /// </summary>
        internal static string Exception_GatewayConnection {
            get {
                return ResourceManager.GetString("Exception_GatewayConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway does not accept password..
        /// </summary>
        internal static string Exception_GatewayConnectionAuthorization {
            get {
                return ResourceManager.GetString("Exception_GatewayConnectionAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway does not accept secure connection certificate  or protocol..
        /// </summary>
        internal static string Exception_GatewayConnectionSecurity {
            get {
                return ResourceManager.GetString("Exception_GatewayConnectionSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        internal static string GatewayError {
            get {
                return ResourceManager.GetString("GatewayError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv4 Address.
        /// </summary>
        internal static string GatewayHost {
            get {
                return ResourceManager.GetString("GatewayHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string GatewayPassword {
            get {
                return ResourceManager.GetString("GatewayPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        internal static string GatewayRequest {
            get {
                return ResourceManager.GetString("GatewayRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responses.
        /// </summary>
        internal static string GatewayResponse {
            get {
                return ResourceManager.GetString("GatewayResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string GatewayState {
            get {
                return ResourceManager.GetString("GatewayState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}s TOC: {1}.
        /// </summary>
        internal static string Info_CatalogToc {
            get {
                return ResourceManager.GetString("Info_CatalogToc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}s TOC: (empty).
        /// </summary>
        internal static string Info_CatalogTocEmpty {
            get {
                return ResourceManager.GetString("Info_CatalogTocEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Value.
        /// </summary>
        internal static string NodeCurrentInteger {
            get {
                return ResourceManager.GetString("NodeCurrentInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Value (%).
        /// </summary>
        internal static string NodeCurrentPercent {
            get {
                return ResourceManager.GetString("NodeCurrentPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forced Value.
        /// </summary>
        internal static string NodeEnforcement {
            get {
                return ResourceManager.GetString("NodeEnforcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string NodeError {
            get {
                return ResourceManager.GetString("NodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing.
        /// </summary>
        internal static string NodeExecuting {
            get {
                return ResourceManager.GetString("NodeExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Identifier.
        /// </summary>
        internal static string NodeIdentifier {
            get {
                return ResourceManager.GetString("NodeIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limitation.
        /// </summary>
        internal static string NodeLimitation {
            get {
                return ResourceManager.GetString("NodeLimitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Value.
        /// </summary>
        internal static string NodeTargetInteger {
            get {
                return ResourceManager.GetString("NodeTargetInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Value (%).
        /// </summary>
        internal static string NodeTargetPercent {
            get {
                return ResourceManager.GetString("NodeTargetPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Value Range.
        /// </summary>
        internal static string OutputRangeAndUnit {
            get {
                return ResourceManager.GetString("OutputRangeAndUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comfort Level 1.
        /// </summary>
        internal static string PriorityComfortLevel1 {
            get {
                return ResourceManager.GetString("PriorityComfortLevel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comfort Level 2.
        /// </summary>
        internal static string PriorityComfortLevel2 {
            get {
                return ResourceManager.GetString("PriorityComfortLevel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comfort Level 3.
        /// </summary>
        internal static string PriorityComfortLevel3 {
            get {
                return ResourceManager.GetString("PriorityComfortLevel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comfort Level 4.
        /// </summary>
        internal static string PriorityComfortLevel4 {
            get {
                return ResourceManager.GetString("PriorityComfortLevel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment Protection.
        /// </summary>
        internal static string PriorityEnvironmentProtection {
            get {
                return ResourceManager.GetString("PriorityEnvironmentProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Protection.
        /// </summary>
        internal static string PriorityHumanProtection {
            get {
                return ResourceManager.GetString("PriorityHumanProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Level 1.
        /// </summary>
        internal static string PriorityUserLevel1 {
            get {
                return ResourceManager.GetString("PriorityUserLevel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Level 2.
        /// </summary>
        internal static string PriorityUserLevel2 {
            get {
                return ResourceManager.GetString("PriorityUserLevel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default (0..51200).
        /// </summary>
        internal static string RangeDefault {
            get {
                return ResourceManager.GetString("RangeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent (0..100).
        /// </summary>
        internal static string RangePercentAsc {
            get {
                return ResourceManager.GetString("RangePercentAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent (100..0).
        /// </summary>
        internal static string RangePercentDesc {
            get {
                return ResourceManager.GetString("RangePercentDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name or :Identifier.
        /// </summary>
        internal static string RequestIdentifier {
            get {
                return ResourceManager.GetString("RequestIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up / Down (Long).
        /// </summary>
        internal static string RequestLongUpDown {
            get {
                return ResourceManager.GetString("RequestLongUpDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min / Max.
        /// </summary>
        internal static string RequestMinMax {
            get {
                return ResourceManager.GetString("RequestMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Priority.
        /// </summary>
        internal static string RequestPriority {
            get {
                return ResourceManager.GetString("RequestPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Value Range.
        /// </summary>
        internal static string RequestRangeAndUnit {
            get {
                return ResourceManager.GetString("RequestRangeAndUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Reboot.
        /// </summary>
        internal static string RequestReboot {
            get {
                return ResourceManager.GetString("RequestReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Reconnect.
        /// </summary>
        internal static string RequestReconnect {
            get {
                return ResourceManager.GetString("RequestReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Type.
        /// </summary>
        internal static string RequestScope {
            get {
                return ResourceManager.GetString("RequestScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up / Down (Short).
        /// </summary>
        internal static string RequestShortUpDown {
            get {
                return ResourceManager.GetString("RequestShortUpDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Source.
        /// </summary>
        internal static string RequestSource {
            get {
                return ResourceManager.GetString("RequestSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop / Start.
        /// </summary>
        internal static string RequestStartStop {
            get {
                return ResourceManager.GetString("RequestStartStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request State.
        /// </summary>
        internal static string RequestState {
            get {
                return ResourceManager.GetString("RequestState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Value.
        /// </summary>
        internal static string RequestTargetInteger {
            get {
                return ResourceManager.GetString("RequestTargetInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Value (%).
        /// </summary>
        internal static string RequestTargetPercent {
            get {
                return ResourceManager.GetString("RequestTargetPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up / Down (Short %).
        /// </summary>
        internal static string RequestUpDownStepSize {
            get {
                return ResourceManager.GetString("RequestUpDownStepSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up / Down (Timespan).
        /// </summary>
        internal static string RequestUpDownTimeSpan {
            get {
                return ResourceManager.GetString("RequestUpDownTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Velocity.
        /// </summary>
        internal static string RequestVelocity {
            get {
                return ResourceManager.GetString("RequestVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string ScopeGroup {
            get {
                return ResourceManager.GetString("ScopeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.
        /// </summary>
        internal static string ScopeNode {
            get {
                return ResourceManager.GetString("ScopeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene.
        /// </summary>
        internal static string ScopeScene {
            get {
                return ResourceManager.GetString("ScopeScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Notification.
        /// </summary>
        internal static string SourceEmergency {
            get {
                return ResourceManager.GetString("SourceEmergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain Sensor.
        /// </summary>
        internal static string SourceRain {
            get {
                return ResourceManager.GetString("SourceRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stand Alone Automatic Control.
        /// </summary>
        internal static string SourceSAAC {
            get {
                return ResourceManager.GetString("SourceSAAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        internal static string SourceTimer {
            get {
                return ResourceManager.GetString("SourceTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninterruptible Power Supply.
        /// </summary>
        internal static string SourceUPS {
            get {
                return ResourceManager.GetString("SourceUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Interaction.
        /// </summary>
        internal static string SourceUser {
            get {
                return ResourceManager.GetString("SourceUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Sensor.
        /// </summary>
        internal static string SourceWind {
            get {
                return ResourceManager.GetString("SourceWind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string VelocityDefault {
            get {
                return ResourceManager.GetString("VelocityDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        internal static string VelocityFast {
            get {
                return ResourceManager.GetString("VelocityFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silent.
        /// </summary>
        internal static string VelocitySilent {
            get {
                return ResourceManager.GetString("VelocitySilent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] velux_cert {
            get {
                object obj = ResourceManager.GetObject("velux_cert", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
