//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace neleo_com.Logic.Control.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("neleo_com.Logic.Control.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cached telegram.
        /// </summary>
        internal static string Cached {
            get {
                return ResourceManager.GetString("Cached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement {0}.
        /// </summary>
        internal static string CaseNumberFilter {
            get {
                return ResourceManager.GetString("CaseNumberFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case statements.
        /// </summary>
        internal static string Cases {
            get {
                return ResourceManager.GetString("Cases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement {0}.
        /// </summary>
        internal static string CaseTextFilter {
            get {
                return ResourceManager.GetString("CaseTextFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger {0}.
        /// </summary>
        internal static string CaseTrigger {
            get {
                return ResourceManager.GetString("CaseTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match.
        /// </summary>
        internal static string CaseUndefinedTrigger {
            get {
                return ResourceManager.GetString("CaseUndefinedTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison Mode.
        /// </summary>
        internal static string Comparison {
            get {
                return ResourceManager.GetString("Comparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defined telegram.
        /// </summary>
        internal static string Defined {
            get {
                return ResourceManager.GetString("Defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string InputNumber {
            get {
                return ResourceManager.GetString("InputNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string InputText {
            get {
                return ResourceManager.GetString("InputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No telegram.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send telegram upon activation.
        /// </summary>
        internal static string SendOnActivation {
            get {
                return ResourceManager.GetString("SendOnActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send telegram upon deactivation.
        /// </summary>
        internal static string SendOnDeactivation {
            get {
                return ResourceManager.GetString("SendOnDeactivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text (neutral).
        /// </summary>
        internal static string TextIgnoreCase {
            get {
                return ResourceManager.GetString("TextIgnoreCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram value upon activation.
        /// </summary>
        internal static string ValueOnActivation {
            get {
                return ResourceManager.GetString("ValueOnActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram value upon deactivation.
        /// </summary>
        internal static string ValueOnDeactivation {
            get {
                return ResourceManager.GetString("ValueOnDeactivation", resourceCulture);
            }
        }
    }
}
