//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace neleo_com.Logic.Timing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("neleo_com.Logic.Timing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity detected.
        /// </summary>
        internal static string ActivityTrigger {
            get {
                return ResourceManager.GetString("ActivityTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (one-time).
        /// </summary>
        internal static string AlarmDateTime {
            get {
                return ResourceManager.GetString("AlarmDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Mode.
        /// </summary>
        internal static string AlarmModeSelector {
            get {
                return ResourceManager.GetString("AlarmModeSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (daily).
        /// </summary>
        internal static string AlarmTime {
            get {
                return ResourceManager.GetString("AlarmTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Trigger.
        /// </summary>
        internal static string AlarmTrigger {
            get {
                return ResourceManager.GetString("AlarmTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Including Parameter {0}.
        /// </summary>
        internal static string CalendarExcludeParameters {
            get {
                return ResourceManager.GetString("CalendarExcludeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluding Parameters.
        /// </summary>
        internal static string CalendarExcludeParametersCount {
            get {
                return ResourceManager.GetString("CalendarExcludeParametersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Including Parameter {0}.
        /// </summary>
        internal static string CalendarIncludeParameters {
            get {
                return ResourceManager.GetString("CalendarIncludeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Including Parameters.
        /// </summary>
        internal static string CalendarIncludeParametersCount {
            get {
                return ResourceManager.GetString("CalendarIncludeParametersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iCal Calendar.
        /// </summary>
        internal static string CalendarInput {
            get {
                return ResourceManager.GetString("CalendarInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snooze/Off.
        /// </summary>
        internal static string ConfirmAlarm {
            get {
                return ResourceManager.GetString("ConfirmAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (one-time).
        /// </summary>
        internal static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Time (daily).
        /// </summary>
        internal static string DefaultTime {
            get {
                return ResourceManager.GetString("DefaultTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Default Time.
        /// </summary>
        internal static string DefaultTimeEnabled {
            get {
                return ResourceManager.GetString("DefaultTimeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Active.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Active.
        /// </summary>
        internal static string EnabledState {
            get {
                return ResourceManager.GetString("EnabledState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        internal static string InputTrigger {
            get {
                return ResourceManager.GetString("InputTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input ports.
        /// </summary>
        internal static string ItemCount {
            get {
                return ResourceManager.GetString("ItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Time.
        /// </summary>
        internal static string LeadTime {
            get {
                return ResourceManager.GetString("LeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send next event.
        /// </summary>
        internal static string NextEventAfter {
            get {
                return ResourceManager.GetString("NextEventAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next event start.
        /// </summary>
        internal static string NextEventBegin {
            get {
                return ResourceManager.GetString("NextEventBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next event summary.
        /// </summary>
        internal static string NextEventSummary {
            get {
                return ResourceManager.GetString("NextEventSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Event Text.
        /// </summary>
        internal static string NextEventSummaryEmpty {
            get {
                return ResourceManager.GetString("NextEventSummaryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event summary format.
        /// </summary>
        internal static string NextEventSummaryFormat {
            get {
                return ResourceManager.GetString("NextEventSummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation Active.
        /// </summary>
        internal static string ObservationActive {
            get {
                return ResourceManager.GetString("ObservationActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation Steps.
        /// </summary>
        internal static string ObservationCount {
            get {
                return ResourceManager.GetString("ObservationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait time {0}.
        /// </summary>
        internal static string ObservationTimeSpans {
            get {
                return ResourceManager.GetString("ObservationTimeSpans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait time {0} over.
        /// </summary>
        internal static string ObservationTriggers {
            get {
                return ResourceManager.GetString("ObservationTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lag time.
        /// </summary>
        internal static string ResetLagTime {
            get {
                return ResourceManager.GetString("ResetLagTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Observation Cycle.
        /// </summary>
        internal static string ResetTrigger {
            get {
                return ResourceManager.GetString("ResetTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Active.
        /// </summary>
        internal static string SequenceActive {
            get {
                return ResourceManager.GetString("SequenceActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm.
        /// </summary>
        internal static string SequenceAlarmTrigger {
            get {
                return ResourceManager.GetString("SequenceAlarmTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snooze.
        /// </summary>
        internal static string SequenceSnoozeTrigger {
            get {
                return ResourceManager.GetString("SequenceSnoozeTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration {0}.
        /// </summary>
        internal static string SequenceStepDuration {
            get {
                return ResourceManager.GetString("SequenceStepDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Steps.
        /// </summary>
        internal static string SequenceSteps {
            get {
                return ResourceManager.GetString("SequenceSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step [0}.
        /// </summary>
        internal static string SequenceStepTrigger {
            get {
                return ResourceManager.GetString("SequenceStepTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snooze Time.
        /// </summary>
        internal static string SnoozeDuration {
            get {
                return ResourceManager.GetString("SnoozeDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and Time {0}.
        /// </summary>
        internal static string StartDateTime {
            get {
                return ResourceManager.GetString("StartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (daily).
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger.
        /// </summary>
        internal static string Trigger {
            get {
                return ResourceManager.GetString("Trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wakeup Date and Time.
        /// </summary>
        internal static string WakeupDateTime {
            get {
                return ResourceManager.GetString("WakeupDateTime", resourceCulture);
            }
        }
    }
}
