//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace neleo_com.Logic.Bridges.Nuki.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("neleo_com.Logic.Bridges.Nuki.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery State.
        /// </summary>
        internal static string BatteryState {
            get {
                return ResourceManager.GetString("BatteryState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge IP.
        /// </summary>
        internal static string BridgeAddress {
            get {
                return ResourceManager.GetString("BridgeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge Token.
        /// </summary>
        internal static string BridgeToken {
            get {
                return ResourceManager.GetString("BridgeToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Identifier.
        /// </summary>
        internal static string DeviceId {
            get {
                return ResourceManager.GetString("DeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Type.
        /// </summary>
        internal static string DeviceType {
            get {
                return ResourceManager.GetString("DeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door State.
        /// </summary>
        internal static string DoorState {
            get {
                return ResourceManager.GetString("DoorState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string GatewayError {
            get {
                return ResourceManager.GetString("GatewayError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        internal static string GatewayRequest {
            get {
                return ResourceManager.GetString("GatewayRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responses.
        /// </summary>
        internal static string GatewayResponse {
            get {
                return ResourceManager.GetString("GatewayResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info (direct).
        /// </summary>
        internal static string InfoAction {
            get {
                return ResourceManager.GetString("InfoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        internal static string LockAction {
            get {
                return ResourceManager.GetString("LockAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock State.
        /// </summary>
        internal static string LockState {
            get {
                return ResourceManager.GetString("LockState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info (cached).
        /// </summary>
        internal static string StateRequest {
            get {
                return ResourceManager.GetString("StateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlatch.
        /// </summary>
        internal static string UnlatchAction {
            get {
                return ResourceManager.GetString("UnlatchAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        internal static string UnlockAction {
            get {
                return ResourceManager.GetString("UnlockAction", resourceCulture);
            }
        }
    }
}
